# Generated by Django 2.1.7 on 2019-04-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log1', models.TextField(default='', max_length=100, null=True)),
                ('log2', models.TextField(default='', max_length=100, null=True)),
                ('log3', models.TextField(default='', max_length=100, null=True)),
                ('log4', models.TextField(default='', max_length=100, null=True)),
                ('log5', models.TextField(default='', max_length=100, null=True)),
                ('log6', models.TextField(default='', max_length=100, null=True)),
                ('log7', models.TextField(default='', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.TextField(default='', max_length=4500, null=True)),
            ],
        ),
    ]
